FROM kasape/repsys:0.4.1

COPY requirements.txt .
RUN pip install --upgrade pip \
    pip install -r requirements.txt

COPY models /app/models
COPY data /app/data
COPY .repsys_checkpoints /app/.repsys_checkpoints
COPY data dataset.py repsys.ini /app/
